[env:seeed_xiao_esp32s3]
platform = espressif32@6.5.0
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 57600
upload_flags =
    --no-stub
build_flags =
    -DATTRAX_ROUND_DISPLAY_PORT
    -DBOARD_SCREEN_COMBO=501
    -DLV_CONF_INCLUDE_SIMPLE
lib_extra_dirs = roundsidplay
lib_deps =
    lvgl/lvgl@^9.2.0
    olikraus/U8g2@^2.34.22
    h2zero/NimBLE-Arduino@^1.4.1
